### ISSUE TITLE
How do I change the log output format?

### ISSUE THREAD

**Issue by bjddd192** [ContentSquare/chproxy#103]
Current:
```sh
DEBUG: 2021/01/19 07:21:29 cache.go:220: cache "shortterm": start cleaning dir "/data/chproxy/cache/shortterm"
DEBUG: 2021/01/19 07:21:29 cache.go:296: cache "shortterm": final size 0; final items 0; removed size 0; removed items 0
```

I hope so:
```sh
2021-01-19 07:21:29.731 DEBUG:  cache.go:220: cache "shortterm": start cleaning dir "/data/chproxy/cache/shortterm"
2021-01-19 07:21:29.732 DEBUG:  cache.go:296: cache "shortterm": final size 0; final items 0; removed size 0; removed items 0
```

Can it be done?

**Comment by mga-chka** [comment]
there is not way to change the output format of the log from chproxy, but you can easily change them when you're reading them using a tool like awk
for example 
`
echo 'DEBUG: 2021/01/19 07:21:29 cache.go:220: cache "shortterm": start cleaning dir "/data/chproxy/cache/shortterm"
' | awk '{printf $2$3 " " $1 "  "} {for (i=4; i<NF; i++) printf $i " "; print $NF}'

2021/01/1907:21:29 DEBUG:  cache.go:220: cache "shortterm": start cleaning dir "/data/chproxy/cache/shortterm"
`
