### ISSUE TITLE
Add chproxy as the prometheus metrics namespace or prefix

### ISSUE THREAD

**Issue by bzon** [ContentSquare/chproxy#105]
It would be nice if the metrics will have a namespace **chproxy** which will prefix each metrics with **chproxy_**.

E.g. chproxy_request_success_total instead of just request_success_total

The problem is that the metric names are commonly used and there is a high chance that aggregating will conflict existing metrics from other jobs in prometheus.

**Comment by gontarzpawel** [comment]
Hello @bzon, I agree with your proposal. Would you mind submitting a PR?

**Comment by mga-chka** [comment]
the current PR https://github.com/ContentSquare/chproxy/pull/221 is linked to this topic

**Comment by mga-chka** [comment]
I'm closing this issue since a namespace was added in https://github.com/ContentSquare/chproxy/pull/221
