### ISSUE TITLE
How to send query/inserts to CH via cproxy in Python/R?

### ISSUE THREAD

**Issue by avraam-inside** [ContentSquare/chproxy#109]
Good afternoon! This connection from under "R" directly to the database works: conn < - DB:: db Connect(R Click house:: clickhouse (), host = 'myhost', user = 'myuser', password = 'mypwd')

But this connection with the proxy address does not work. Probably because the address is a proxy server, not a clickhouse database.

At the same time, in the ssh connection settings, the address of the destination database is often requested, and I have a cluster of 4 servers and I use chproxy, so that it does not connect to a specific database, but to one of the 4.

Please advise pliz on how to connect to the database from under R/Python. Preferably with a sample code.

**Comment by WesleyBatista** [comment]
Perhaps you could provide tracebacks or even a reproducible example?

Regarding the problem itself, you can maybe check the timeout settings when connecting.

**Comment by gontarzpawel** [comment]
Provided that @avraam-inside didn't share reproducible example, I'm closing this issue.
