### ISSUE TITLE
When will a new version available?

### ISSUE THREAD

**Issue by tochka** [ContentSquare/chproxy#112]

**Comment by vfoucault** [comment]
Why do you need a new version ? Are we talking about a feature that is missing and that you want to add ?

**Comment by tochka** [comment]
Yes, for us, the important features are 
- fix caching for select queries in body requests. #96 
- fix caching for queries with 'WITH' #108

Also, we're waiting to solve #121

**Comment by vfoucault** [comment]
If you are un a rush of a new version, you built it yourself, create your container and deploy it.

In the coming weeks there should be some changes around the CI process that would leverage goreleaser and more cool features.

**Comment by mga-chka** [comment]
FYI the ownership of CHProxy has been transfered to the ContentSquare company recently.
We're still looking at what should be prioritised by we should release a new version within a few months

**Comment by gontarzpawel** [comment]
New version has been released, you can find it here https://github.com/ContentSquare/chproxy/releases/tag/v1.15.0
