### ISSUE TITLE
[Future request] Detect concurrent identical user's query

### ISSUE THREAD

**Issue by podhornyi** [ContentSquare/chproxy#114]
Sometimes user will send the same heavy query to CH multiple times in a row, however he able to do some other query at the same time - in case if user is Grafana/Metabase/etc.
So to handle this kind of situation solutions is:
 
- detect identical concurrent queries per user
- send them in virtual queue until first one running on CH
- after first query returned to client, send result of another ones to user from cache
- as a bonus, all these identical queries will take only 1 place in a queue - if max_queue_size defined in config

This feature already implemented in #113

**Comment by gontarzpawel** [comment]
Hi @podhornyi, as answered in the mentioned PR this feature already exists. Therefore I close this issue
