### ISSUE TITLE
[Feature Request] Cache settings in days

### ISSUE THREAD

**Issue by iShift** [ContentSquare/chproxy#12]
Now i can set cache settings in seconds, but for heavy requests (in my project) i use cache for 3-7 days it would be good if i can set settings in days.

Example:
Now i use  expire: 259000s
i want:  expire: 3d

**Comment by hagen1778** [comment]
Hi @iShift 
Currently it supports standard Go-durations, like "24s", "24m", "24h". But it might be useful to support  days also. Stay tuned)

**Comment by hagen1778** [comment]
It supports `d` (days) and `w` (weeks) now:
`<duration>`: a duration matching the regular expression `^([0-9]+)(w|d|h|m|s|ms|µs|ns)`

check new release https://github.com/Vertamedia/chproxy/releases/tag/1.9.0

**Comment by iShift** [comment]
Thanks!
