### ISSUE TITLE
include a play page

### ISSUE THREAD

**Issue by rlazimi-dev** [ContentSquare/chproxy#123]
ClickHouse nodes provide a page ([http interface](https://clickhouse.tech/docs/en/interfaces/http/)) for sending queries through http.

**My request is that chproxy also acts as a reverse proxy for this interface**.

I suggest that one can control which node they are routed to using query parameters. I also suggest that if this routing query parameter is not provided, chproxy will default to random routing toward the nodes (this way the feature is easier to bookmark).

**Comment by gontarzpawel** [comment]
Hello @rlazimi-dev, we haven't planned this in near future. I'm not sure how would you like it to work. 
Feel free to propose a design and use cases envisioned

**Comment by mga-chka** [comment]
I'm closing the issue.
@rlazimi-dev if you want to provide a design, feel free to reopen it.
