### ISSUE TITLE
Support `/ping` endpoint

### ISSUE THREAD

**Issue by mr-karan** [ContentSquare/chproxy#127]
Clickhouse returns a `HTTP 200` response for `/ping` URL. However, this library doesn't support proxying that.

I want to add that `/metrics` won't work always, because that is optional and moreover, user can set any value for metrics endpoint (as mentioned here: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-prometheus)

`/ping` should be the standard way to do healthchecks. 

> In health-check scripts use GET /ping request. This handler always returns “Ok.” (with a line feed at the end). Available from version 18.12.13.

https://clickhouse.com/docs/en/interfaces/http/

Additionally, queries on `/` are also proxied to `/query` which feels wrong too.

> If you make a GET / request without parameters, it returns 200 response code and the string which defined in http_server_default_response default value “Ok.” (with a line feed at the end)

^ To conform to the API of Clickhouse, I believe the proxy should behave the same.

**Comment by vfoucault** [comment]
Hi @mr-karan,

It seems right to align chproxy on clickhouse api.

Feel free to issue a PR to fix this is you know how.

**Comment by gontarzpawel** [comment]
Hi @mr-karan , this feature has been released along with the version `v0.17.0`

**Comment by allen12921** [comment]
@gontarzpawel 
I still get ```unsupported path: "/ping" ``` with the latest chproxy ver. 1.21.0
Is there any configs missed?

**Comment by jtprogru** [comment]
In 1.25.0 endpoint `/ping` is not supported.

Endpoint `/ping` should be added in this section if I understand the structure of the project correctly:

https://github.com/ContentSquare/chproxy/blob/v1.25.0/main.go#L215

**Comment by ssube** [comment]
Is this supported in recent versions? I am also getting `unsupported path: "/ping"` errors on the server side, which looks like the code at https://github.com/ContentSquare/chproxy/blob/master/main.go#L252. I don't see a `case` for "`/ping"` there - what am I missing?

**Comment by pkesso** [comment]
![image (18)](https://github.com/user-attachments/assets/4be17246-6ee8-47f4-a953-14d744da8cb9)

The problem persists in 1.26.4. 
VS Code (and any other client performs /ping check before connect) would throw an error 'unsupported path: "/ping"'

**Comment by mga-chka** [comment]
FYI, we're already handling the /ping, so there must be a recent issue, cf [this PR](https://github.com/ContentSquare/chproxy/pull/214)

**Comment by fengshao01** [comment]
I also just ran into the same issue when using sqltool extension to connect to chproxy.

**Comment by pkesso** [comment]
@mga-chka isn't it /ping between chpoxy and server? Because there is a problem between client and chproxy.

**Comment by kiendo01** [comment]
Hi, Please reopen this issue as it is not resolve. This is not a problem between chproxy and clickhouse, this is a problem between clickhouse client and chproxy. VSCode client cannot connect to clickhouse proxy because of unsupported path: "/ping"

**Comment by mga-chka** [comment]
yes there is indeed an issue. It was fixed on this PR https://github.com/ContentSquare/chproxy/pull/456
We will do a release this week that contains the fix

**Comment by mga-chka** [comment]
you can use the new 1.26.5 version of chproxy that should fix this issue for good.
