### ISSUE TITLE
Allow `param_` in query parameters

### ISSUE THREAD

**Issue by junekiwi** [ContentSquare/chproxy#128]
I understand from the README and #98 that query parameters are filtered to prevent unwanted overrides of ClickHouse parameters.

However, this also filters parameters starting with `param_` which are used to replace placeholders in parametrized queries[^1].
For example `SELECT * FROM {table:Identifier}` with `param_table=some_table`.

Is there any security reasons to disallow these parameters?
I'd say that, on the contrary, allowing them would improve the (overall) security since it allows the use of parametrized queries instead of client-side string interpolation.

I'm having success with this in production, but I don't know if this breaks other parts of the code (caching?):
```patch
diff --git a/scope.go b/scope.go
index 951f927..7c4985c 100644
--- a/scope.go
+++ b/scope.go
@@ -343,6 +343,13 @@ func (s *scope) decorateRequest(req *http.Request) (*http.Request, url.Values) {
 		}
 	}
 
+	// Keep parametrized queries params
+	for param := range origParams {
+		if strings.HasPrefix(param, "param_") {
+			params.Set(param, origParams.Get(param))
+		}
+	}
+
 	// Keep external_data params
 	if req.Method == "POST" {
 		ct := req.Header.Get("Content-Type")
```

[^1]: https://clickhouse.com/docs/en/interfaces/http/#cli-queries-with-parameters

**Comment by gontarzpawel** [comment]
Hello @maxmouchet,

thanks for reaching out. There would be indeed an impact on caching if you do not modify how cache key is created. Here's a scenario where your change would cause undesired bahaviour:
- req 1 
```
curl -v "http://default:@localhost:9090/query?param_table=table1" -d "select * from {table:Identifier}  FORMAT JSON;"
```
- req 2
```
curl -v "http://default:@localhost:9090/query?param_table=table2" -d "select * from {table:Identifier}  FORMAT JSON;"
```

these 2 queries are identical, so they'll lead to the same cache key. However, request 2 relates to the completely different table, therefore cache key shouldn't be shared.

You should additionally add it to the `cache.Key` structure
https://github.com/ContentSquare/chproxy/blob/ee67a2da681668f838efc10bf2bf0a492903cefa/proxy.go#L273

A PR would be very much welcomed 🙂

**Comment by tomerr-neosec** [comment]
Is this going to be solved soon?

**Comment by gontarzpawel** [comment]
The PR has just been merged. New version will be released shortly!
