### ISSUE TITLE
Randomise ports of Clickhouse and Redis mocks in tests

### ISSUE THREAD

**Issue by gontarzpawel** [ContentSquare/chproxy#139]
## Motivation
In order to support parallel CI executions we need to improve current testing framework to have randomised ports for Clickhouse and Redis.

## Specifics
All the tests rely on static configuration (yaml) to bootstrap chproxy server and execute on it particular test scenario. In those there are ports for Clickhouse and Redis hardcoded.

**Comment by sigua-cs** [comment]
@mga-chka @gontarzpawel 
Hello guys,
There are a few ways to achieve that.

Define a function that checks the open TCP port and returns the number. The function should be available for all packages as we have `testing` functions per package. To achieve that, we have two options:
 1. Create `MainTest` function using `testing.M` struct and define the random open ports for Redis and ClickHouse mocks as global variables. As a result, both ports should be available as variables for all `testing.T` functions.
2. Create a `utils` package in the root module, and the randomized ports function within. The function will be available from every package in the project.

Additionally, we can define static ports for Redis and ClickHouse from the 10000 - 65536 range. For example, Redis port 16379 and ClickHouse 18123. This option, for me less preferred but easier to troubleshoot.

What do you think guys?

**Comment by mga-chka** [comment]
I'm closing this issue since a tradeoff was made: using dedicated but very exotic ports for both redis & clickhouse during the tests
