### ISSUE TITLE
(Redis cache) Add the possibility to have a specific cache per user

### ISSUE THREAD

**Issue by mga-chka** [ContentSquare/chproxy#154]
For security issues, some companies need that each sql user has their own cache.
Indeed, if clickhouse is configured with [ROW policies](https://clickhouse.com/docs/en/sql-reference/statements/create/row-policy/) or other kind of user rights, a user could have access to forbidden data if the query was previously done by another user with the right access and the result is is already cached in CH Proxy.

**Comment by Nicholaswang** [comment]
working in progress

**Comment by Nicholaswang** [comment]
@mga-chka Hi, to avoid misunderstanding, do you have a more detailed description or specification of the requirement for this issue?

**Comment by mga-chka** [comment]
Hi (sorry for the late reply),
The current issue with the Redis Cache design is that:
- we have 2 users "john" & "jane" has different read right in clickhouse (for example jane is not allowed to see the information of the row "Barack Obama" in the table persons)
- john do a query about information forbidden for jane ("in my example select * from persons where id="[the id barack obama")
- the result will be cached into chproxy
- if jane does the same queries as john, she will be able to see the forbidden data because chproxy will give the result from the cache & the security layer inside clickhouse won't be called.

Before doing the task, please explain how you want to solve the problem because it would be sad if you do a big PR and we refuse it because we think the way you did it is too complex.

**Comment by mga-chka** [comment]
@Nicholaswang FYI I'll do the task since we need it ASAP at contentsquare and we didn't hear from you about the task

**Comment by mga-chka** [comment]
cf https://github.com/ContentSquare/chproxy/pull/258 for the ongoing PR fixing this behavior

**Comment by Nicholaswang** [comment]
Great, got caught up in other things recently, I will also try out the new PR as soon as possible.
