### ISSUE TITLE
Transparent users

### ISSUE THREAD

**Issue by ilejn** [ContentSquare/chproxy#169]
Hello, 
as far as I can any user who accesses chproxy must be listed in config.
This approach effectively disables LDAP advanced usage https://clickhouse.com/docs/en/operations/external-authenticators/ldap/#ldap-external-user-directory .
If I am not mistaken is it possible to pass user names via chproxy transparently? Ideally by wildcards.
Thanks.

**Comment by ilejn** [comment]
PR https://github.com/ContentSquare/chproxy/pull/170 is awaiting for review/discussion/approval/whatever.

**Comment by mga-chka** [comment]
Sorry, we're a bit busy for the moment, we will review this PR in 1 or 2 weeks

**Comment by ilejn** [comment]
We've introduced a new concept https://hackmd.io/LXk8tLI8Q3etKax-HWtGxQ and a new PR https://github.com/ContentSquare/chproxy/pull/219

**Comment by mga-chka** [comment]
closing the issue since PR https://github.com/ContentSquare/chproxy/pull/219 was merged
