### ISSUE TITLE
user custom session_id_type

### ISSUE THREAD

**Issue by ddddddcf** [ContentSquare/chproxy#174]
sometime when I set param of `session_id` , I just want proxy some queries to the same machine instead of query with context .Unfortunately , Clickhouse does not support concurrent queries with the same `session_id` , exception `Session is locked by a concurrent client. (SESSION_IS_LOCKED)` will occur . So I think should add optional param let user custom session_id type, like `proxy_without_context_by_sessionId` and `proxy_with_context_by_sessionId `

**Comment by gontarzpawel** [comment]
Hello @ddddddcf , is the issue resolved following the #173 ?

**Comment by ddddddcf** [comment]
> 

This issue solves the problem of routing the same session_id to different nodes

**Comment by ddddddcf** [comment]
> Hello @ddddddcf , is the issue resolved following the #173 ?

This issue solves the problem of routing the same session_id to different nodes
