### ISSUE TITLE
[BUG] chproxy return wrong error message: ClickHouse exception, code: 1002, host: xxx.xxx.com, port: 80; 

### ISSUE THREAD

**Issue by ryze124** [ContentSquare/chproxy#183]
**Describe the bug**
when i select a not exists , chproxy return wrong error code：ClickHouse exception, code: 1002, host: xxx.xxx.com, port: 80;  .

**To Reproduce**
4 clickhouse nodes，2 shards，2 replications.
2 chproxy instances,  1 nginx proxy which use http
table name（which not exists）：default.table_not_exists
sql: select count(1) from default.table_not_exists

**Expected behavior**
it should return table not found exception. like the following:
![image](https://user-images.githubusercontent.com/13214153/177673408-25bbd64d-daa8-42ed-81f4-ccf618a7c937.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/13214153/177673158-8b1e803e-d4a5-41b2-bd08-e580c91a02c9.png)

**Environment information**
OS version: CentOS 7.9, chproxy ver. 1.15.1 and Clickhouse version: 21.3.3.14

**Additional context**

**Comment by mga-chka** [comment]
If you have time, it would be worth checking if the issue only happens for this exception or if it's broader which is what I guess (meaning: every CH error will generate a blurrier exception on CHProxy side).
I tag this issues as enhancement and not bug since it's just a labeling pb.

**Comment by mga-chka** [comment]
[edited since this message was for another issue]

**Comment by gontarzpawel** [comment]
Hi @1241407808 , it looks like it was related to #192 . We will shortly release a fix version and we're looking forward to hear back from you if the issue is resolved 🙂

**Comment by ryze124** [comment]
Thanks .
After you release a fix version , i  will try it again . Then , close this  issue.

**Comment by gontarzpawel** [comment]
Hi @1241407808 , 
the release is done https://github.com/ContentSquare/chproxy/releases/tag/v1.16.2

**Comment by mga-chka** [comment]
once you confirm it fixed your pb we'll close this issue

**Comment by ryze124** [comment]
it fixed in 1.16.2
