### ISSUE TITLE
[Feature] Retry recoverable requests

### ISSUE THREAD

**Issue by gontarzpawel** [ContentSquare/chproxy#185]
**Is your feature request related to a problem? Please describe.**
Today, when proxied requests to specific shard fail we simply fail the client request, even if the failure happens due to shard's unavailability.  

**Describe the solution you'd like**
When request fails due to unavailable shard it is routed to another replica.  

**Additional context**
It would allow restart of clickhouse servers without impacting end user.

Function that should be changed (matching on recoverable http status code): https://github.com/ContentSquare/chproxy/blob/11d2412d8d256f016fa6787d02fed5378fcf3719/proxy.go#L145

We should add a possibility to get the next replica. For that scope will have to be modified
https://github.com/ContentSquare/chproxy/blob/11d2412d8d256f016fa6787d02fed5378fcf3719/scope.go#L55

**Comment by gontarzpawel** [comment]
FYI @mga-chka @sigua-cs @LEijsackersCS Jingmao will take care of this enhancement.

**Comment by mga-chka** [comment]
IMHO the number of retries must be configurable and at 0 by default.

**Comment by LEijsackersCS** [comment]
We can also maintain the shard health on CHProxy side and use that to make routing decisions. If a shard is unhealthy it can be skipped (as opposed to retrying with a different shard). But for now I'm ok with retrying.

**Comment by gontarzpawel** [comment]
@LEijsackersCS this information is already stored in chproxy, but you may launch a query in-between healthchecks. Therefore the status of the node is not updated yet.

**Comment by LEijsackersCS** [comment]
We do need both indeed. I was just thinking of an overloaded node and then retrying requests against that will make the node less likely to recover.

**Comment by gontarzpawel** [comment]
> We do need both indeed. I was just thinking of an overloaded node and then retrying requests against that will make the node less likely to recover.

We're marking the node as inactive if it does not respond to healthcheck, so load balancing algorithm will not use it for the next queries.
