### ISSUE TITLE
[Feature] Docker arm64 images

### ISSUE THREAD

**Issue by dantecoding** [ContentSquare/chproxy#204]
Hello, guys, can you build arm64 or maybe another architectures docker images in docker hub, thanks?

**Comment by mga-chka** [comment]
Hi,
@sigua-cs will check if it doesn't take too much time and if it's simple enough he will do it

**Comment by sigua-cs** [comment]
Hello @dantecoding , we added builds for arm64 to docker images. You can try the latest release v1.16.4
Feel free to reopen this issue or a new one
I'm closing this issue
