### ISSUE TITLE
chproxy log is incorrect, how to solve it

### ISSUE THREAD

**Issue by bigdata-spec** [ContentSquare/chproxy#236]
![image](https://user-images.githubusercontent.com/23710717/191702333-356a6c87-5921-4581-880a-b2c860eb7519.png)

The time zone in the chproxy log is incorrect, how to solve it？

**Comment by mga-chka** [comment]
CH proxy relies on golang logs package using UTC and not the local timezone:
https://github.com/ContentSquare/chproxy/blob/master/log/log.go#L12
This might be why you're having this behavior. 
For the moment the UTC is hardcoded (cf the code I gave you) and there is no way to switch to the local time zone. So if you want the same time, you should switch your server to UTC.

Feel create a PR to let the choice of UTC vs local timezone in the config.yml
