### ISSUE TITLE
documentation does not match the release

### ISSUE THREAD

**Issue by DenisGee** [ContentSquare/chproxy#243]
so, documentation https://www.chproxy.org/configuration/users has information about is_wildcarded but in last release(v1.17.2) the functionality does not work

**Comment by mga-chka** [comment]
good point.
We wanted to make a release of v1.17.3 (that contains the new wildcarded user feature) sooner but we're waiting for a last fix before doing it, this new version (aligned with the documentation) should be released within a week.

**Comment by mga-chka** [comment]
FYI the version 1.18.0 of chproxy with the wildcarded user feature is released
