### ISSUE TITLE
[Feature] allow more patterns for wildcarded users

### ISSUE THREAD

**Issue by mga-chka** [ContentSquare/chproxy#249]
**Is your feature request related to a problem? Please describe.**
As discussed with @DenisGee in the PR about wildcarded users here (https://github.com/ContentSquare/chproxy/pull/219#issuecomment-1279185370), the feature is only limited for usernames that matches the pattern [prefix]_[wildcard]

**Describe the solution you'd like**
We should be able to use this feature for more pattern of usernames.
At least:
- [prefix][wildcard]
- [wildcard][suffix]
- [willdcard]

**Describe alternatives you've considered**
the pattern with multiple wildcards or [prefix][wildcard][suffix] might be more complex to handle in an efficient way (since it involves regexp) so they're not considered for the moment.

**Additional context**
For security reason, the default user should not be usable with this feature

**Comment by mga-chka** [comment]
this change will be available in the future 1.19.0 that will be released within a week

**Comment by DenisGee** [comment]
Thank you for so fast reaction and the merge
