### ISSUE TITLE
[QUESTION] Strange benchmarking

### ISSUE THREAD

**Issue by ilejn** [ContentSquare/chproxy#264]
Hello, I am trying to benchmark chproxy. 
Instead of ClickHouse I use nginx that is tweaked to support healthchecks.
Three nodes, one runs ab (client), another chproxy and the third one is nginx.

The result is rather decent 
```
[ilejn@golshtein-centos-2 ~]$ ab -t 10 -c 20 -k 'http://10.92.16.214:9090/?query=SELECT%201'
This is ApacheBench, Version 2.3 <$Revision: 1430300 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 10.92.16.214 (be patient)
Completed 5000 requests
Completed 10000 requests
Completed 15000 requests
Completed 20000 requests
Completed 25000 requests
Finished 27211 requests


Server Software:        nginx/1.18.0
Server Hostname:        10.92.16.214
Server Port:            9090

Document Path:          /?query=SELECT%201
Document Length:        612 bytes

Concurrency Level:      20
Time taken for tests:   10.001 seconds
Complete requests:      27211
Failed requests:        0
Write errors:           0
Keep-Alive requests:    27211
Total transferred:      22830029 bytes
HTML transferred:       16653132 bytes
Requests per second:    2720.91 [#/sec] (mean)
Time per request:       7.350 [ms] (mean)
Time per request:       0.368 [ms] (mean, across all concurrent requests)
Transfer rate:          2229.34 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       1
Processing:     1    7   3.3      7      41
Waiting:        1    7   3.3      7      41
Total:          1    7   3.3      7      41

Percentage of the requests served within a certain time (ms)
  50%      7
  66%      8
  75%      9
  80%      9
  90%     10
  95%     13
  98%     15
  99%     19
 100%     41 (longest request)
```
While after a while I see significant performance degradation (same test, 10 times longer)
```
[ilejn@golshtein-centos-2 ~]$ ab -t 100 -c 20 -k 'http://10.92.16.214:9090/?query=SELECT%201'
This is ApacheBench, Version 2.3 <$Revision: 1430300 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 10.92.16.214 (be patient)
Completed 5000 requests
Completed 10000 requests
Completed 15000 requests
Completed 20000 requests
Completed 25000 requests
Completed 30000 requests
Completed 35000 requests
Completed 40000 requests
Completed 45000 requests
Completed 50000 requests
Finished 50000 requests


Server Software:        nginx/1.18.0
Server Hostname:        10.92.16.214
Server Port:            9090

Document Path:          /?query=SELECT%201
Document Length:        612 bytes

Concurrency Level:      20
Time taken for tests:   61.051 seconds
Complete requests:      50000
Failed requests:        6157
   (Connect: 0, Receive: 0, Length: 6157, Exceptions: 0)
Write errors:           0
Non-2xx responses:      6157
Keep-Alive requests:    50000
Total transferred:      39142022 bytes
HTML transferred:       28259954 byFailed requests:        6157tes
Requests per second:    818.99 [#/sec] (mean)
Time per request:       24.420 [ms] (mean)
Time per request:       1.221 [ms] (mean, across all concurrent requests)
Transfer rate:          626.11 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       1
Processing:     1   24  44.1      9     484
Waiting:        1   24  44.1      9     484
Total:          1   24  44.1      9     484

Percentage of the requests served within a certain time (ms)
  50%      9
  66%     11
  75%     13
  80%     15
  90%     80
  95%    124
  98%    180
  99%    217
 100%    484 (longest request)
```
Note, that RPS is 3 timew lower in the second test.
What is may be even more important, there is a number of request failures (Non-2xx responses:      6157) in the longer test.
This is 'Bad Gateway''.

chproxy utilizes two available CPU cores, nginx something like 10% and hardly can be a bottleneck.

Direct communication with nginx does not show any issues
```
[ilejn@golshtein-centos-2 ~]$ ab -t 100 -c 20  'http://10.92.6.192:8124/?query=SELECT%201'
This is ApacheBench, Version 2.3 <$Revision: 1430300 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 10.92.6.192 (be patient)
Completed 5000 requests
Completed 10000 requests
Completed 15000 requests
Completed 20000 requests
Completed 25000 requests
Completed 30000 requests
Completed 35000 requests
Completed 40000 requests
Completed 45000 requests
Completed 50000 requests
Finished 50000 requests


Server Software:        nginx/1.18.0
Server Hostname:        10.92.6.192
Server Port:            8124

Document Path:          /?query=SELECT%201
Document Length:        612 bytes

Concurrency Level:      20
Time taken for tests:   10.540 seconds
Complete requests:      50000
Failed requests:        0
Write errors:           0
Total transferred:      42700000 bytes
HTML transferred:       30600000 bytes
Requests per second:    4744.05 [#/sec] (mean)
Time per request:       4.216 [ms] (mean)
Time per request:       0.211 [ms] (mean, across all concurrent requests)
Transfer rate:          3956.46 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    2   3.3      2      52
Processing:     0    2   3.4      2      52
Waiting:        0    2   3.4      1      52
Total:          1    4   6.1      3      83

Percentage of the requests served within a certain time (ms)
  50%      3
  66%      3[ilejn@golshtein-centos-2 ~]$ ab -t 100 -c 20  'http://10.92.6.192:8124/?query=SELECT%201'
This is ApacheBench, Version 2.3 <$Revision: 1430300 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 10.92.6.192 (be patient)
Completed 5000 requests
Completed 10000 requests
Completed 15000 requests
Completed 20000 requests
Completed 25000 requests
Completed 30000 requests
Completed 35000 requests
Completed 40000 requests
Completed 45000 requests
Completed 50000 requests
Finished 50000 requests


Server Software:        nginx/1.18.0
Server Hostname:        10.92.6.192
Server Port:            8124

Document Path:          /?query=SELECT%201
Document Length:        612 bytes

Concurrency Level:      20
Time taken for tests:   10.540 seconds
Complete requests:      50000
Failed requests:        0
Write errors:           0
Total transferred:      42700000 bytes
HTML transferred:       30600000 bytes
Requests per second:    4744.05 [#/sec] (mean)
Time per request:       4.216 [ms] (mean)
Time per request:       0.211 [ms] (mean, across all concurrent requests)
Transfer rate:          3956.46 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    2   3.3      2      52
Processing:     0    2   3.4      2      52
Waiting:        0    2   3.4      1      52
Total:          1    4   6.1      3      83

Percentage of the requests served within a certain time (ms)
  50%      3
  66%      3
  75%      4
  80%      4
  90%      5
  95%      6
  98%     26
  99%     45
 100%     83 (longest request)
  75%      4
  80%      4
  90%      5
  95%      6
  98%     26
  99%     45
 100%     83 (longest request)
```

I am digging into this at the moment.
Hints and suggestions are highly appreciated.

**Comment by ilejn** [comment]
Configuration is trivial
```
server:
  http:
      listen_addr: ":9090"
      allowed_networks: ["10.92.0.0/16"]
users:
  - name: "default"
    to_cluster: "default"
    to_user: "default"
clusters:
  - name: "default"
    users:
       - name: "default"
    nodes: ["10.92.6.192:8124"]
```

**Comment by mga-chka** [comment]
I don't know what could be the issue but it seems weird.
My first guess is that it's linked to the garbage collection that could be heavy on some edge cases and slow down everything but I don't understand the bad gateway.
In chproxy we don't generate 502 errors so it either comes from nginx or the httputil.reverseProxy we're using ([an official go package](https://pkg.go.dev/net/http/httputil#ReverseProxy) that can generate 502 )

Could you do the same test with the filesystem cache  activated to be sure the issue is not linked to nginx?
Other question, did you activate error logs in nginx to be sure there are no 502 generated from nginx?

**Comment by ilejn** [comment]
Hello, please advise how to calculate required RAM if cache is disabled.
Is it safe to assume that chproxy requires <512k per active query, IOW if maximum number of parallel queries is 200 one needs 100M of RAM (which is practically nothing)?

**Comment by ilejn** [comment]
Hello @mga-chka , many thanks for the response.

Currently I am 99% sure that BadGateway comes from proxyRequest()
```
        // StatusBadGateway response is returned by http.ReverseProxy when
        // it cannot establish connection to remote host.
        if srw.statusCode == http.StatusBadGateway {
            s.host.penalize()
```
It turned out that nginx is not required because ClickHouse is fast enough at queries like SELECT 1 to serve as backend to benchmark chproxy. Behaviour is the same.

I'll continue the investigation. Plan to enable ReverseProxy logs.

**Comment by mga-chka** [comment]
`
Hello, please advise how to calculate required RAM if cache is disabled.
Is it safe to assume that chproxy requires <512k per active query, IOW if maximum number of parallel queries is 200 one needs 100M of RAM (which is practically nothing)?
`
I'm not sure if 100M of RAM is enough because:
- go needs memory for it's inner working
- because of the way go garbage collection works, you need at least 2 more memory than the raw data (maybe 3 times more, I don't rememeber)
- even if the http query done to chproxy are small, the overhead of the http headers (and http) on chproxy side and on clickhouse side might increase the memory footprint
- It didn't check but I think there are some duplication of the http query (not the result from clickhouse) in the code so you might have a multiplier in terms of memory consumption

Can you try the same bench with much more memory on chproxy side?
If it's just an issue about memory usage, IMHO it's not worth spending more time since your benchmark with an high & constant QPS doesn't look like a real usage (since clickhouse was meant for low QPS).

**Comment by ilejn** [comment]
Hello Christophe,
I have 8Gb RAM on the test box which must be enough for a couple of dozens of connections.
I hope that my question about RAM is not related (thank for the answer though).

I've checked several theories with no luck.
Recently I've realized that there are many random connect() errors like
```
ERROR: 2022/11/10 12:30:17 scope.go:699: error while health-checking "10.92.6.192:8124" host: cannot send request in 10.622882ms: Get "http://10.92.6.192:8124/ping": dial tcp 10.92.6.192:8124: connect: cannot assign requested address
```
and that
```
$ sudo netstat -anp | grep WAIT | wc -l
28252
```
At first glance this is something about SO_REUSEADDR.
Looking into this.

**Comment by ilejn** [comment]
Hello Christophe,
further observations.
1. My test environment (and our production environment) is CentOS 7. I cannot reproduce the issue on Ubuntu 22.04 (don't know why).
2. The issue can be solved by increasing MaxIdleConnsPerHost in Transport that is used by ReverseProxy. Current value is 2, which is nothing. Assuming the number of ClickHouse hosts served by an instance of chproxy is relatively small, I assume that it is safe to have MaxIdleConnsPerHost, say, 1000.

**Comment by ilejn** [comment]
The patch is as simple as
```
diff --git a/proxy.go b/proxy.go
index 2607beb..7d181b1 100644
--- a/proxy.go
+++ b/proxy.go
@@ -6,6 +6,7 @@ import (
 	"errors"
 	"fmt"
 	"io"
+	"net"
 	"net/http"
 	"net/http/httputil"
 	"net/url"
@@ -47,6 +48,20 @@ type reverseProxy struct {
 	hasWildcarded bool
 }
 
+var customizedTransport http.RoundTripper = &http.Transport{
+	Proxy: http.ProxyFromEnvironment,
+	DialContext: (&net.Dialer{
+		Timeout:   30 * time.Second,
+		KeepAlive: 30 * time.Second,
+	}).DialContext,
+	ForceAttemptHTTP2:     true,
+	MaxIdleConns:          100,
+	IdleConnTimeout:       90 * time.Second,
+	TLSHandshakeTimeout:   10 * time.Second,
+	ExpectContinueTimeout: 1 * time.Second,
+	MaxIdleConnsPerHost:   100,
+}
+
 func newReverseProxy() *reverseProxy {
 	return &reverseProxy{
 		rp: &httputil.ReverseProxy{
@@ -54,7 +69,8 @@ func newReverseProxy() *reverseProxy {
 
 			// Suppress error logging in ReverseProxy, since all the errors
 			// are handled and logged in the code below.
-			ErrorLog: log.NilLogger,
+			ErrorLog:  log.NilLogger,
+			Transport: customizedTransport,
 		},
 		reloadSignal: make(chan struct{}),
 		reloadWG:     sync.WaitGroup{},
```
The only what I've actually changed is MaxIdleConnsPerHost, others parameters are intact.

To be honest, I am not sure what to do.
1. The problem is rather serious for old Linuxes, so it must be solved. On the other hand, nobody cares.
2. The idea to hardcode '100' seems strange. On the other hand, having it configurable seems too heavy-weight.

Advice?

**Comment by ilejn** [comment]
About the nature of the issue.
Assume that chproxy closes TCP connection to ClickHouse.
The connection remains in TIME_WAIT state for 60 (may be 30) seconds, so the port had used by the connection cannot be reused for the ClickHouse instance for this perioud of time.
The only remedy - persistent connections.

**Comment by mga-chka** [comment]
Thanks for the info.
FYI there is also a change to do in the killqueries & heatbeat codes (that uses their own transport layer):
* https://github.com/ContentSquare/chproxy/blob/master/scope.go#L279
* https://github.com/ContentSquare/chproxy/blob/master/heartbeat.go#L57

If the behavior is only on old kernels (that shouldn't be used for security issues) AND when the QPS stays high for a long time it looks like a rare issue. IMHO putting a warning in the doc might be enough. Are you sure there is nothing to tweak on OS side?

Persistent connections might be a good solution but it seems to be an heavy task (I'm a bit worried about the side effects). We want to focus on making chproxy compatible with TCP (from user to chroxy and chproxy to clickhouse) so we won't have time in the next 6 months for such a change.

**Comment by ilejn** [comment]
Hello @mga-chka 
1. I'll look into kill queries and heartbeat code, thanks.
2. I cannot say for sure that the problem is typical for old kernels only, I just don't have enought statistics. Although I think that yes.
3. It is a hot topic about tweaking OS. see https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux for example . Related parameters are net.ipv4.tcp_tw_recycle and net.ipv4.tcp_tw_reuse  , it is possible to increase port range. It may be possible to reduce timeout, though I am not sure. 
4. about persistent connections. It seems that I was not clear enough. **chproxy already uses persistent connections** and what I suggest is increasing the number of such connections. 

See my patch above, it proved to be helpful. When it is applied everything works fine in CentOS 7.

**Comment by ilejn** [comment]
BTW, binary protocol in chproxy is cool!

**Comment by mga-chka** [comment]
my worry about your fix is:
* the 100 magical number
* the potential side effects. For example it could lead to file descriptor issues on OSs that have a low FD limit (the limit was at 1024 by default on my ubuntu) and produce crashes in production once people upgrade chproxy and encounter spikes of load.

One tradeoff would be to put that in the config so that the chproxy admin can chose the value or use the default value (2).
You can make a PR with an optional field in the config if this is a critical issue but I still believe it's not worth it since chproxy is not aimed for high QPS and (gut feeling) most clickhouse users have recent kernels (if the issue is really with kernel version).

**Comment by ilejn** [comment]
1. Yes, agree. But MaxIdleConns is a magical number as well. And we already have it (see net/http/transport.go)
2. Theoretically yes, agree about FD shortage risk under very special kind of load. In reality 98 file decriptors (100-2) do not look too serious.

**Comment by mga-chka** [comment]
@sigua-cs @Garnek20 @Blokje5 what do you think, should we raise the number of MaxIdleConnsPerHost & MaxIdleConns from  2 (default value) to 100?

**Comment by ilejn** [comment]
I have to admit that the ratio 100:100 (MaxIdleConnsPerHost:MaxIdleConns) is suboptimal because one host can eat the whole pool. 
While 2:100 is suboptimal as well e.g. because 50 is above the number of nodes in an average ClickHouse cluster.

Maybe make both MaxIdleConnsPerHost and MaxIdleConns configurable with defaults 10 and 100 respectively?

**Comment by Blokje5** [comment]
From my understanding of the issues, I am fine with exposing the settings to configuration and making it configurable. The ratio of MaxIdleConns/MaxIdleConnsPerHost should indeed be similar to the ChProxy Nodes/Clickhouse Nodes ratio (ideally). I

t also depends on the number of requests that are sent to CHProxy of course, but if we make it configurable it can be tweaked for extreme cases.

We can expose it in the configuration and document what the ideal settings are.

**Comment by mga-chka** [comment]
I'm closing this issue since the PR solving the pb was merged
