### ISSUE TITLE
[Feature] tmpDir temporary path cannot be configured

### ISSUE THREAD

**Issue by woozhijun** [ContentSquare/chproxy#285]
Hi, 
CHProxy  tmpDir is default /tmp，cannot be configured.

In this way, there will often be insufficient disk space

```
: cannot create temporary file in "/tmp": open /tmp/tmp4211204731: no space left on device;
```

Hope to provide a solution as soon as possible.

**Comment by sigua-cs** [comment]
Hello @woozhijun , thanks for reporting the issue.
/tmp is the part of root volume. You can mount /tmp on dedicated disk or increase the root volume size

**Comment by woozhijun** [comment]
> 
Hi  @sigua-cs 
When I mount /tmp on dedicated disk，The system not allow。

`rmdir: failed to remove ‘tmp/’: Device or resource busy`

**Comment by woozhijun** [comment]
@sigua-cs    It is suggested whether configuration can be supported？

**Comment by sigua-cs** [comment]
@woozhijun I missed your response message. Sorry about that. Let me check few things and get back to you

**Comment by sigua-cs** [comment]
@woozhijun can you please provide more info about the setup and environment? Does it runs in k8s, Docker on VM, etc.

**Comment by sigua-cs** [comment]
> 

I believe you should mount the volume to /tmp without deleting it

**Comment by sigua-cs** [comment]
@woozhijun did you manage to solve it on your side?

**Comment by mga-chka** [comment]
I'm closing this issue since it's stale. Feel free to reopen it if needed.
