### ISSUE TITLE
[BUG] executeWithRetry is not work

### ISSUE THREAD

**Issue by jiachinzhao** [ContentSquare/chproxy#293]
**Describe the bug**
executeWithRetry is not work
<img width="594" alt="image" src="https://user-images.githubusercontent.com/17783623/216273357-a896727b-9870-4005-8705-7526554b7e5b.png">
 the reason is req.Body can   only be readed once.  
when req.Body is readed by one clickhouse and clickhouse shutdown,  executeWithRetry to another clickhouse  will lead to 400 bad request, since req.Body will be empty

**To Reproduce**
Steps to reproduce the behavior.

set 2 backend clickhouse-server
set config retry_number > 0
1. send request to chproxy
2. shutdown one clickhouse
3. request will failed

**Expected behavior**

**Screenshots**

**Environment information**
Information about OS, chproxy and Clickhouse versions on which issue occures.

**Additional context**

**Comment by mga-chka** [comment]
Thanks for the issue, FYI I warned the creators of this feature. They'll take a look at it within a few days.

**Comment by gontarzpawel** [comment]
Hello @jiachinzhao, can you tell us if the issue is present for both POST and GET requests? From your description it sounds that retry mechanism does not work while chproxy used with POST

**Comment by mga-chka** [comment]
since the PR fixing the issue was merged, I'm closing this issue.
We will try to release a new version of chproxy next week.
Feel free to reopen the issue is the fix is not enough
