### ISSUE TITLE
[QUESTION] Is there an API open

### ISSUE THREAD

**Issue by FWLamb** [ContentSquare/chproxy#321]
**Question details**
Because we need to integrate chproxy into the platform, it would be even better if there were APIs open.

**Comment by mga-chka** [comment]
Hi, chproxy is exposing the same http calls as clickhouse so you should check if clickhouse provides an open API (I don't think so). On chproxy side, we have a specfic API (i.e. not provided by clickhouse) regarding metrics. We don't provide a swagger like interface to describe them. You can find the information about this API here https://www.chproxy.org/configuration/metrics
