### ISSUE TITLE
[QUESTION] set to TLSv1.2 in https_config

### ISSUE THREAD

**Issue by yeungp** [ContentSquare/chproxy#323]
**Which feature your question relates to?**
https_config

**Question details**
How do I configure chproxy to only use TLSv1.2?   And not to use SSLv2, SSLv3, TLSv1.1 or TLSv1.3.
Does chproxy support specifying a list of ciphers to use?

**Additional context/motivations**
We setup an ALB in front of multiple chproxy in AWS GovCloud.  The GovCloud ALB does not support TLSv1.3, and we are required to use TLSv1.2.

**Comment by mga-chka** [comment]
it weird because TLS 1.2 should work. Can you try with v1.19.0? Because on 1.20.0 we did a change on TLS that prevent using TLS 1.1 and older.

**Comment by mga-chka** [comment]
@yeungp were you able to test with v1.19.0?
