### ISSUE TITLE
[BUG] X-Forwarded-For parsing is incorrect 

### ISSUE THREAD

**Issue by andreitoupinets** [ContentSquare/chproxy#326]
**Describe the bug**
Chproxy use ", " (comma with space) as a separator for elements in header. In result, when chproxy receives request from GCP HTTP load balancer, it ignores header at all, because GCP LB use only comma symbol (space is optional by RFC7239).

**To Reproduce**
curl -i -H "x-forwarded-for: 1.1.1.1,2.2.2.2" asdf@127.0.0.1:8123/?query=select%201

**Expected behavior**
Removing of space fix this issue:
```
+++ b/proxy_handler.go
@@ -74,7 +74,7 @@ func extractFirstMatchFromIPList(ipList string) string {
 	if ipList == "" {
 		return ""
 	}
-	s := strings.Index(ipList, ", ")
+	s := strings.Index(ipList, ",")
 	if s == -1 {
 		s = len(ipList)
 	}
@@ -91,7 +91,7 @@ func parseForwardedHeader(fwd string) string {
 	for _, split := range splits {
 		trimmed := strings.TrimSpace(split)
 		if strings.HasPrefix(strings.ToLower(trimmed), "for=") {
-			forSplits := strings.Split(trimmed, ", ")
+			forSplits := strings.Split(trimmed, ",")
 			if len(forSplits) == 0 {
 				return ""
 			}
```

**Comment by mga-chka** [comment]
Hi, thanks for the issue. We will check if your proposal doesn't create new issue then make a fix.

**Comment by Blokje5** [comment]
I should be able to look into this this week, I will pick it up.

**Comment by mga-chka** [comment]
@Blokje5 my 2 cents since I started to look.
It seems to be a missing case when we implemented the feature since in the RFC 7239, this case case happen
```   Note that an HTTP list allows white spaces to occur between the
   identifiers, and the list may be split over multiple header fields.
   As an example, the header field

       Forwarded: for=192.0.2.43,for="[2001:db8:cafe::17]",for=unknown

   is equivalent to the header field

       Forwarded: for=192.0.2.43, for="[2001:db8:cafe::17]", for=unknown
```
I quickly looked at the code and the fix doesn't seem dangerous. I let you have a second look then apply the fix (or not).

**Comment by mga-chka** [comment]
FYI the version containing the fix should be released btw 1 or 3 weeks
