### ISSUE TITLE
Set queue priority 

### ISSUE THREAD

**Issue by sablastik** [ContentSquare/chproxy#331]
Is it possible somehow to push query inside queue?
For example: in the moment i have a queue of 30 queries and i need some query to be executed as fast as possible. 
May be by adding some parameter to a query?

**Comment by mga-chka** [comment]
There is currently no way to bypass the priority inside a queue for a specific user.

That being said as simple conf could do what you want we one trade-off:
You create 2 users:
* You have your "normal user " with a dedicated queue
* You have a "priority user" with a dedicated queue

You can sent most of your queries with the normal user and the rare important ones on the priority user. The tradeoff is that you might have up to twice more queries running concurrently in your cluster (but if the amount of high priority queries is low, it shouldn't be an issue).

**Comment by sablastik** [comment]
ok, i see. i hope there will be such feature in future. thank you
