### ISSUE TITLE
Docker-compose healthcheck path is wrong

### ISSUE THREAD

**Issue by petrenko-hilbert** [ContentSquare/chproxy#340]
https://github.com/ContentSquare/chproxy/blob/a09b62ebdbd14c2a06f96e0995fdd95d78547d4e/examples/quick_start/docker-compose.yml#L79

Hello! Using docker image `contentsquareplatform/chproxy:v1.24.0` 
Suggested healthcheck URL for docker compose doesn't work, I get
`ERROR: 2023/05/31 17:31:51 main.go:254: "172.23.0.1:50136": unsupported path: "/ping"`
It won't work neither for quick start compose config, nor for chproxy I try to set up with existing clusters

Who has to answer that healthcheck actually? It that chproxy itself, or should it forward this request to any or one of configured clusters?

**Comment by sigua-cs** [comment]
Hello @petrenko-hilbert . The healthcheck answer comes from Chproxy.  We use `/metrics` path for that

**Comment by petrenko-hilbert** [comment]
Thank you, that indeed works!
It's probably better to update the example
