### ISSUE TITLE
Using chproxy for accessing clickhouse replication cluster, but 9001 is not in listen state

### ISSUE THREAD

**Issue by venkip541** [ContentSquare/chproxy#349]
Hi Team

We are exploring clickhouse with replication and sharding configuration.We have setup 4 node cluster with 2 shards with replication enabled. 

Two shard S1,S2 with  replicas (R1,R2) and (R3,R4) respectively. We created distributed tables to access the data from all the shards and able to insert/fetch the data. To test the failure scenario, we have shutdown R3 and R4 forcefully to check whether we are able to fetch the data from the available shards(S1) from (R1,R2). But, we are not getting exceptions while trying to query from distributed table from R1/R2.

While exploring we came across chrproxy that could interact with clickhouse clusters for handling this issue.

https://clickhouse.com/docs/en/interfaces/third-party/proxy
https://stackoverflow.com/questions/55133418/is-there-someway-to-make-distributed-table-still-work-for-query-when-one-of-the

We have configured the same by following the respective document but 9001 port is not in listen state even the service is up and running, below is the configuration defined for chproxy

hack_me_please: true
log_debug: true

server:
  http:
    listen_addr: ":9090"

users:
  - name: "posthog_cluster"
    allowed_networks: [
      "10.0.3.0/24",
      "10.0.4.0/24",
      "10.0.6.0/24"
      ]
    to_cluster: "clickhouse_posthog"
    to_user: "posthog"
    max_concurrent_queries: 6
    max_execution_time: 1m

  - name: "signoz_cluster"
    allowed_networks: [
      "10.0.3.0/24",
      "10.0.4.0/24",
      "10.0.6.0/24"
      ]
    to_cluster: "clickhouse_signoz"
    to_user: "signoz"
    max_concurrent_queries: 6
    max_execution_time: 1m

clusters:
  - name: "clickhouse_posthog"
    nodes: [
      "ip-node-1.ap-south-1.compute.internal:8123",
      "ip-node-2.ap-south-1.compute.internal:8123",
      "ip-node-3.ap-south-1.compute.internal:8123",
      "ip-node-4.ap-south-1.compute.internal:8123"
       ]
    users:
      - name: "default"

      - name: "posthog"
        password: "*********"

  - name: "clickhouse_signoz"
    nodes: [
      "ip-node-1.ap-south-1.compute.internal:8123",
      "ip-node-2.ap-south-1.compute.internal:8123",
      "ip-node-3.ap-south-1.compute.internal:8123",
      "ip-node-4.ap-south-1.compute.internal:8123"
       ]
    users:
      - name: "signoz"
        password: "*********"

Please help us on fixing the same.

BR
Venkatesh. P

**Comment by ardenwick** [comment]
you configured chproxy to listen on port 9090 here:

> listen_addr: ":9090"
