### ISSUE TITLE
[QUESTION] "read_timeout: 5m" parameter is invalid.

### ISSUE THREAD

**Issue by Toroidals** [ContentSquare/chproxy#369]
**Which feature your question relates to?**
E.g caching with redis, user authentication...

**Question details**
In the server configuration under "http:", the parameter "read_timeout: 5m" is set. However, when querying, it still throws an error "read_timeout" after approximately 30 seconds of querying time.

**Additional context/motivations**
Is there any info or motivation to be shared? E.g. asking the question because started to investigate if chproxy's feature X is suitable for my use case.

**Comment by mga-chka** [comment]
Hi, the read_timeout you're referring to is the timeout of the proxy. It means than if you run a query and it takes more than 5 minutes you'll get this error. But, it doesn't mean you can't get a timeout before 5 min if, for example, your clickhouse is supposed to timeout after 30 sec (look at the `max_execution_time` to override it) or if you're using redis and it times out (there is no way to change the timeout of redis but it's something like a few seconds, which is A LOT for a key value store like redis).
