### ISSUE TITLE
Caching with redis, database selection

### ISSUE THREAD

**Issue by Mitsukiro** [ContentSquare/chproxy#379]
**Which feature your question relates to?**
Caching with redis, database selection

**Question details**
I observed that when initializing the cache on the Redis side, there is no provision to specify the database number for Redis itself. I believe this could be beneficial in certain scenarios.

It's about passing the DB [int] parameter to
https://github.com/ContentSquare/chproxy/blob/master/clients/redis.go#L12

Is it possible to implement such a feature?

**Additional context/motivations**

**Comment by Blokje5** [comment]
As it is only passing configuration, it shouldn't be too hard to implement a PR for this. If you want @Mitsukiro you can open a PR. I am happy to help & review the PR.

**Comment by Mitsukiro** [comment]
@Blokje5, I appreciate your prompt response. Adding a configuration parameter doesn't seem like a difficult task. I will open a PR as soon as time permits. Thanks.
