### ISSUE TITLE
timeout for user errors

### ISSUE THREAD

**Issue by adiletkabylbekov** [ContentSquare/chproxy#391]
i faced a lot of errors related to query timeout
`timeout for user \"user\" exceeded: 2m0s;`
and chproxy was going to kill such queries

in the description of configuration, default value for `max_execution_time` is no limit
```
# Maximum duration of query execution for user
# By default there is no limit on the query duration.
max_execution_time: <duration> | optional | default = 0
```
https://github.com/ContentSquare/chproxy/blob/master/config/README.md

i was confused, because `max_execution_time` wasn't set in my env, so it should be set as default value - no limit
and i didn't understand why queries killed by timeout from chproxy side

actually in code base i found that there is set limit as default value - 120s 
https://github.com/ContentSquare/chproxy/blob/2600c0e234ab949baffd3f1f223f836b72418640/config/config.go#L47
https://github.com/ContentSquare/chproxy/blob/2600c0e234ab949baffd3f1f223f836b72418640/config/config.go#L858-L862
please, fix the config description or fix it on code parts

**Comment by mga-chka** [comment]
good catch, we will change the doc

**Comment by mga-chka** [comment]
this PR containing the fix will soon be merged so I'm closing this issue.
