### ISSUE TITLE
[Feature] Change status code to concurrent query failed on cancelled requests

### ISSUE THREAD

**Issue by NatSau02** [ContentSquare/chproxy#404]
**Is your feature request related to a problem? Please describe.**
When sending concurrent queries with a syntax error, the response "500, concurrent query failed" is returned, although the clickhouse responds to such errors with 400 (screenshot). The same behavior is observed for requests with 404

**Describe the solution you'd like**
500 is a service error that requires attention and correction, I think it would be more accurate to return the status of the clickhouse response so that there are no differences and the response is more informative

**Additional context**
<img width="999" alt="image" src="https://github.com/ContentSquare/chproxy/assets/73480958/ab8ba866-2673-496a-a5bf-bf6bdd4a615e">

**Comment by NatSau02** [comment]
PR https://github.com/ContentSquare/chproxy/pull/405

**Comment by mga-chka** [comment]
FYI all the maintainers are a bit busy for the moment, we will review your 2 PR and issues next week

**Comment by NatSau02** [comment]
https://github.com/ContentSquare/chproxy/issues/406 this solution was recognized as the best
