### ISSUE TITLE
[Feature Request] Support prepared statements

### ISSUE THREAD

**Issue by winem** [ContentSquare/chproxy#41]
Actually, this might be a bit out of scope for a plain proxy but in some of projects the only reason for a client facing self-written middleware instead of just the chproxy is that we want to have another abstraction layer in between and prevent users from running super expensive queries and for example. 

I see that this is anything but not simple and fast but I think that this would increase the value of chproxy a lot. 

Would love to see the support for prepared statements in the future. 

Let me know if you need more details. 

Best regards,
Marcel

**Comment by valyala** [comment]
The idea looks interesting. But it is unclear how to configure prepared statements in simple and maintainable way. @winem , could you propose something in this direction?

**Comment by winem** [comment]
@valyala this is also a bit unclear to me. I see how this could work with simple select statements for example but I see the "challenge" once we get to real complex queries for example. I will think about it in the next days and come back when I have something. 
Right now, I'm torn between a solution that has some limitations on the scope of supported queries and my preference for generic "scalable" solutions.

**Comment by gontarzpawel** [comment]
Hello @winem, it's been a long time since you created the issue. Have you given it a second thought though?

**Comment by mga-chka** [comment]
Hi, since the discussion is stalled, I'm closing the issue.
Feel free to reopen the issue if there is something new on this topic.
