### ISSUE TITLE
[QUESTION] why only one replica node in each shard have a high load？

### ISSUE THREAD

**Issue by fankuneee** [ContentSquare/chproxy#412]
[https://github.com/ClickHouse/ClickHouse/issues/61716#issue-2200405050](url)

Why, when sending a select to a ClickHouse cluster with multiple replicas, does only one replica node in each shard have a high load, while the other replica nodes have a low load, causing the node with high load to be unavailable at times?

I have 8 ClickHouse nodes, 4 shards, and 2 replicas per shard. I'm using chproxy for load balancing across my cluster. However, the result is that in each shard, only one replica is overloaded while the other remains idle. Are there any configuration options or solutions to resolve this issue?

also the load_balancing option in my config.xml is round_robin,but it seems not working.

and I use Distributed Table Engine

clickhouse-server version: v22.10.6.3-stable
chproxy： 1.20.1

**Comment by mga-chka** [comment]
can you try with a version >= 1.25 or < 1.20?
Cf this [bug fix](https://github.com/ContentSquare/chproxy/blob/master/CHANGELOG.md?plain=1#L34), there was an issue on the load balancing logic, it might explain your problem.
