### ISSUE TITLE
[QUESTION]  Availability of max_query_size Flag in Chproxy

### ISSUE THREAD

**Issue by mrankitsinghal** [ContentSquare/chproxy#433]
**Question: Availability of max_query_size Flag in Chproxy**

**Question details**
In our use case with ClickHouse, we often encounter the need to pass larger queries. While the max_query_size flag works seamlessly with ClickHouse directly, we've encountered errors when using it with Chproxy. Can someone confirm whether the max_query_size flag is available in Chproxy?

**Additional context/motivations**
The `max_query_size` parameter is supported by ClickHouse within Query statements, aiding in the handling of larger queries.

**Comment by mga-chka** [comment]
indead you can use this flag. One way to have it in chproxy is to write it in the clickhouse query using the `SETTINGS` keyword. For example: `select * from system.numbers limit 1  settings max_query_size= 400`, would it solve your issue?

**Comment by Blackmorse** [comment]
I have the similar issue, not able to pass the `max_query_size` while using chproxy, while directly with Clickhouse it works.

@mga-chka, Actually passing it along with the query in `SETTINGS` section will not work: Clickhouse needs to have that setting BEFORE parsing the query, according to the docs: 
https://clickhouse.com/docs/operations/settings/settings#max_query_size
