### ISSUE TITLE
Ability to configure allowedParams

### ISSUE THREAD

**Issue by jpiper** [ContentSquare/chproxy#45]
We have some clients that send "max_result_rows" (I'm looking at you, JDBC connector!) and we liked that chproxy stripped this out as readonly users can't change this parameters. It would be good if the allowedParams could be configured

**Comment by valyala** [comment]
It is possible to configure `max_result_rows` and other options on per-user level with `param_groups` and `params` options in `chproxy` config. Search for these options in [the README.md](https://github.com/Vertamedia/chproxy/blob/master/README.md) for more information.

**Comment by gontarzpawel** [comment]
Issue was answered, closing it. Feel free to comment if there are any things unclear.
