### ISSUE TITLE
[BUG] VSCode clickhouse client cannot connect to chproxy: unsupported path: "/ping"

### ISSUE THREAD

**Issue by kiendo01** [ContentSquare/chproxy#475]
**Describe the bug**
When connect to chproxy using VSCode client, the client throw errors:
```
 unsupported path: "/ping"
```

**To Reproduce**
- Install chproxy by docker-compose
- Install Sqltools extension and Clickhouse driver for SQLTools extension
- Try to connect

**Expected behavior**
Connection successful

**Screenshots**

**Environment information**
OS: Linux
Click house version: 24.7.6.8
Chproxy: 1.24.0

**Additional context**

**Comment by mga-chka** [comment]
cf the lastest comments on https://github.com/ContentSquare/chproxy/issues/127, I'm closing this one since it should be fixed now
