### ISSUE TITLE
identical request should be able to be refused after grace time elapse

### ISSUE THREAD

**Issue by nineteenthSpring** [ContentSquare/chproxy#51]
I think identical request should be able to be refused after grace time elapse. but I spot that all remain requests have been delegated to clickhouse servers after first request timeout. and no options can be configured. when set grace_time: -1s, the server can't be started.  display error:  can't load config "/data/service/ck-proxy/config.yml": not a valid duration string: "-1s"

**Comment by hagen1778** [comment]
Thanks for report! It looks like a bug to me but I can't provide no guarantees when it will be fixed. PR's are welcome.
cc @valyala

**Comment by gontarzpawel** [comment]
Fix for that has been released following the commit #146
