### ISSUE TITLE
[Feature Request] Support listen ipv6 

### ISSUE THREAD

**Issue by orloffv** [ContentSquare/chproxy#55]
https://github.com/Vertamedia/chproxy/blob/master/main.go#L118

Maybe setting in config - enableTCP6

**Comment by hagen1778** [comment]
see https://github.com/Vertamedia/chproxy/pull/67

**Comment by gontarzpawel** [comment]
Hello @orloffv, 
this feature will be available within the next release, see #133 
I'll close this issue. Feel free to reopen in case of further questions
