### ISSUE TITLE
The network pressure of CHProxy will be great?

### ISSUE THREAD

**Issue by xunliu** [ContentSquare/chproxy#95]
Ask a question. If data is written to Clickhouse through CHProxy, will all the traffic of data writing go through the routine of CHProxy? If this is the case, the network pressure of CHProxy will be great?

**Comment by gontarzpawel** [comment]
Hello @xunliu , could you elaborate? I don't think I've understood.

**Comment by mga-chka** [comment]
since this discussion is stalled I'm closing it.
Feel free to reopen it if needed
