### ISSUE TITLE
Is it possible to dynamically redirect a request to a specific cluster?

### ISSUE THREAD

**Issue by OmarBazaraa** [ContentSquare/chproxy#97]
Consider that I have 10 clusters and 2 users: 1 for writing and 1 for reading.

I want to be able to dynamically map an incoming request to a specific cluster based on a hint in the query parameters.
I don't want to define 20 users. Is that possible?

**Comment by gontarzpawel** [comment]
Hello @OmarBazaraa, no it is not. You'd have to create 20 users.
