### ISSUE TITLE
Proxy strips query params

### ISSUE THREAD

**Issue by simPod** [ContentSquare/chproxy#98]
I'm sending the request with params like `max_query_size`. I would like to forward it to my replica through proxy. 

Currently the proxy seems to strip it. Is there a way to disable it?

**Comment by hagen1778** [comment]
Hi @simPod! Proxy strips GET params for a reason. Pls see https://github.com/Vertamedia/chproxy/blob/master/scope.go#L292 and https://github.com/Vertamedia/chproxy#security.

**Comment by simPod** [comment]
@hagen1778 thank you for the link. But what if I want to allow other params? There seems to be a no way to override or disable the behaviour. I'd like the chproxy to proxy and leave the rest to ClickHouse instances.

**Comment by hagen1778** [comment]
I understand the frustration. The list of params is static since it is used in the cache key. So in order to extend/control it on demand - the hash package should be updated accordingly. It might be not that easy to implement and I don't have time to work on this project anymore. So any help will be appreciated. On the other hand, you can just make a fork and update the list of params manually for your case.

**Comment by simPod** [comment]
Thank you for the answer, that leads me to slightly off topic question: what is the future of the project? :D Do I understand that any further maintenance is not planned except for OSS contributions? Thanks!

**Comment by hagen1778** [comment]
I'll try to review PRs, respond to questions or fix critical issues. It is unlikely for me to work on any additional features so far. However, I'm not the only maintainer - @valyala wdyt?

**Comment by gontarzpawel** [comment]
> Thank you for the answer, that leads me to slightly off topic question: what is the future of the project? :D Do I understand that any further maintenance is not planned except for OSS contributions? Thanks!

Hello @simPod, Contentsquare decided to continue evolution of the project. Therefore, you might expect new feature to arrive 🙂  The first one is already there - #135 distributed cache

**Comment by Blokje5** [comment]
Closing this as this is the same issue as #338, which proposes an config option to allow for unsafe overrides.
